hall_of_fans_icon = '//XCUIElementTypeImage[@name="hall_of_fans"]'
register_popup_title = '//XCUIElementTypeStaticText[@name="Please, register on the knight club app to continue."]'
register_popup_cancel_button = '//XCUIElementTypeButton[@name="Cancel"]'
register_popup_ok_button = '//XCUIElementTypeButton[@name="Ok"]'
video_button = '//XCUIElementTypeButton[@name="VIDEOS"]'
newpay_button = '//XCUIElementTypeButton[@name="btn newplay"]'
video_play = '//XCUIElementTypeStaticText[@name="Videos"]'
fan_loyalty_program_menu = '//XCUIElementTypeStaticText[@name="FAN LOYALTY PROGRAM"]'
