fan_chat = '//android.widget.TextView[@resource-id="com.knightclub.app:id/btn_fan_chat"]'

join_button = '(//android.widget.Button[@resource-id="com.knightclub.app:id/btn_join"])[replace_group]'

join_success_toast = '//android.widget.Toast[@text="Group joined successfully!!!"]'
write_msg_text = '//android.widget.EditText[@resource-id="com.knightclub.app:id/etComposeBox"]'
group_back_button = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/iv_back_arrow"]'
send_button = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/ivSend"]'

skip_button = '//android.widget.TextView[@resource-id="com.knightclub.app:id/textSkip"]'
joined_button = '//android.widget.Button[@resource-id="com.knightclub.app:id/btn_join" and @text="JOINED"]'

add_club_button = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/ivArrow"]'

take_photo = '//android.widget.TextView[@resource-id="com.knightclub.app:id/camera_message"]'
take_picture_button = '//android.view.ViewGroup[@content-desc="Take picture"]'
camera_ok_button = '//android.widget.Button[@content-desc="OK"]'
current_date = '//android.widget.TextView[@resource-id="com.knightclub.app:id/txt_time" and @text="05:49 pm"]'

gify_icon = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/ivGif"]'
first_gif = '(//android.widget.ImageView[@resource-id="com.knightclub.app:id/ivGif"])[1]'
group_icon = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/iv_chat_avatar"]'
group_username = '//android.widget.TextView[@resource-id="com.knightclub.app:id/txt_user_name" and @text="You"]'
files_tab = '//android.widget.TextView[@text="FILES"]'
leave_group_button = '//android.widget.TextView[@resource-id="com.knightclub.app:id/tv_exit"]'
leave_group_confirm_message = '//android.widget.Button[@resource-id="android:id/button1"]'
first_join_button = '(//android.widget.Button[@resource-id="com.knightclub.app:id/btn_join"])[1]'
create_poll_button = '//android.widget.TextView[@resource-id="com.knightclub.app:id/poll_message"]'
enter_question_field = '//android.widget.EditText[@resource-id="com.knightclub.app:id/et_question"]'
enter_option1 = '(//android.widget.EditText[@resource-id="com.knightclub.app:id/et_option"])[1]'
enter_option2 = '(//android.widget.EditText[@resource-id="com.knightclub.app:id/et_option"])[2]'
create_poll = '//android.widget.Button[@resource-id="com.knightclub.app:id/btn_create_poll"]'
poll_question = '//android.widget.TextView[@resource-id="com.knightclub.app:id/tv_question"]'
administrators_button = '//android.widget.TextView[@text="Administrators"]'
Assign_group_admin_option = '//android.widget.TextView[@resource-id="com.knightclub.app:id/add_as_tv"]'
group_member = '//android.widget.TextView[@resource-id="com.knightclub.app:id/txt_user_name" and @text="test team"]'
yes_button = '//android.widget.Button[@resource-id="android:id/button1"]'
group_username1 = '//android.widget.TextView[@resource-id="com.knightclub.app:id/txt_user_name"]'
search_button_field = '//android.widget.EditText[@resource-id="com.knightclub.app:id/et_search"]'
fan_chat_search_button = '//android.widget.ImageButton[@resource-id="com.knightclub.app:id/text_input_end_icon"]'
navigate_back = '//android.widget.ImageButton[@content-desc="Navigate up"]'
group_list_section = '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.knightclub.app:id/rvFanClubs"]'
group_name = '(//android.widget.TextView[@resource-id="com.knightclub.app:id/tvFanClubName"])[replace_index]'
message_list = '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.knightclub.app:id/rv_message_list"]'
laughing_emoji = '//android.widget.TextView[@resource-id="com.knightclub.app:id/tv_reaction" and @text="😄"]'
message_react_button = '//android.widget.Button[@text="😄 1"]'
reply_message_id = '//android.widget.TextView[@resource-id="com.knightclub.app:id/reply_message"]'

latest_message_time = '//android.widget.TextView[@resource-id="com.knightclub.app:id/txt_time" and @text="latest_time"]'
latest_message_xpath = '(//android.widget.ImageView[@resource-id="com.knightclub.app:id/go_img_message"])[latest_message]'
replay_latest_msg = '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.knightclub.app:id/rv_message_list"]/android.widget.LinearLayout[message]'
pinned_messages_option = '//android.view.ViewGroup[@resource-id="com.knightclub.app:id/cl_pinned_messages"]'
pin_message = '//android.widget.TextView[@resource-id="com.knightclub.app:id/pin_message"]'
pin_message_toast = '//android.widget.Toast[@text="Pinned successfully!!!"]'
sent_message = '//android.widget.ImageView[@resource-id="com.knightclub.app:id/go_img_message"]'
latest_sent_message = '(//android.widget.ImageView[@resource-id="com.knightclub.app:id/go_img_message"])[index]'
react_message = '//android.widget.RelativeLayout[@resource-id="com.knightclub.app:id/cv_message_container"]'
moderator_button = '//android.widget.TextView[@text="Moderators"]'
assign_moderator_button = '//android.widget.TextView[@resource-id="com.knightclub.app:id/add_as_tv"]'
go_back = '//android.widget.ImageButton[@content-desc="Navigate up"]'

message_sent = '//android.widget.TextView[@resource-id="com.knightclub.app:id/go_txt_message"]'

