hall_of_fans_checkbox= '//XCUIElementTypeButton[@name="un check box"]'
check_leaderboard_popup_logo = '//XCUIElementTypeImage[@name="hiFan_logo"]'
check_leaderboard_popup_title = '//XCUIElementTypeStaticText[@name="HI FANS!"]'
check_leaderboard_popup_description = '//XCUIElementTypeStaticText[@name="Check if you are on our Leaderboard. Achieve top position on the leaderboard to win exclusive Knight Rider experiences."]'
check_leaderboard_popup_ok_button = '//XCUIElementTypeButton[@name="Ok"]'
leaderboard_screen_title = '//XCUIElementTypeStaticText[@name="FANS RANKING"]'
top_fans_background = '//XCUIElementTypeImage[@name="top_fans_background"]'
