profile_image = '//XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeImage'
lakr_primary_team_logo = '//XCUIElementTypeStaticText[@name="LAKR"]'
coupon_earned_popup_ok_button = '//XCUIElementTypeButton[@name="OK"]'
my_profile_icon = '//XCUIElementTypeButton[@name="replace_initial"]'
invite_a_friend_button = '//XCUIElementTypeButton[@name="INVITE A FRIEND"]'
referral_popup_title = '//XCUIElementTypeStaticText[@name="REFERRAL"]'
share_via_button = '//XCUIElementTypeButton[@name="  Share Via"]'
edit_player_button = '//XCUIElementTypeButton[@name="EDIT"]'
select_player_dropdown = '//XCUIElementTypeStaticText[@name="FAVOURITE PLAYER"]//preceding-sibling::XCUIElementTypeTextField'
save_player_button = '//XCUIElementTypeButton[@name="SAVE"]'
related_video_first_like_button = '(//XCUIElementTypeStaticText[@name="RELATED VIDEOS"]//preceding-sibling::XCUIElementTypeButton[@name="flrp like icon"])[1]'
related_photos_first_like_button = '(//XCUIElementTypeStaticText[@name="RELATED PHOTOS"]//following-sibling::XCUIElementTypeButton[@name="Like"])[1]'
related_news_first_like_button = '(//XCUIElementTypeStaticText[@name="RELATED NEWS"]//following-sibling::XCUIElementTypeButton[@name="flrp like icon"])[1]'
related_photos_first_liked_button = '//XCUIElementTypeStaticText[@name="RELATED PHOTOS"]//following-sibling::XCUIElementTypeButton[@name="flrp liked icon"]'
related_video_first_liked_button = '(//XCUIElementTypeStaticText[@name="RELATED VIDEOS"]//preceding-sibling::XCUIElementTypeButton[@name="flrp liked icon"])[1]'
related_news_first_liked_button = '(//XCUIElementTypeStaticText[@name="RELATED NEWS"]//following-sibling::XCUIElementTypeButton[@name="flrp liked icon"])[1]'
related_video_first_share_button = '(//XCUIElementTypeStaticText[@name="RELATED VIDEOS"]//preceding-sibling::XCUIElementTypeButton[@name="new share icon"])[1]'
share_popup_knight_club_link = '//XCUIElementTypeStaticText[@name="knightclub.page.link"]'
share_popup_close_button = '//XCUIElementTypeButton[@name="Close"]'
related_video_title = '//XCUIElementTypeStaticText[@name="RELATED VIDEOS"]'
related_photo_title = '//XCUIElementTypeStaticText[@name="RELATED PHOTOS"]'
